"""Increase api_key length

Revision ID: 9997bfbc462f
Revises: 
Create Date: 2025-11-25 12:44:55.400293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9997bfbc462f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller_accounts', 'api_key',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=600),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller_accounts', 'api_key',
               existing_type=sa.String(length=600),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###
